import React, { useState } from 'react';
import {
  X,
  User,
  Phone,
  Mail,
  MapPin,
  Calendar,
  Briefcase,
  DollarSign,
  Download,
  Plus,
  Play,
  Volume2,
  CheckCircle,
  Clock,
  Sparkles,
  Shield,
  FileText,
} from 'lucide-react';
import { Candidate, CandidateStatus } from '../../types/database';
import { StatusBadge } from '../common/StatusBadge';
import { AudioPlayerWidget } from '../common/AudioPlayerWidget';
import { INITIAL_CALLS } from '../../data/mockData';

interface CandidateDetailModalProps {
  candidate: Candidate | null;
  isOpen: boolean;
  onClose: () => void;
  onStatusChange: (candidateId: string, newStatus: CandidateStatus) => void;
  onAddNote: (candidateId: string, noteText: string) => void;
}

export const CandidateDetailModal: React.FC<CandidateDetailModalProps> = ({
  candidate,
  isOpen,
  onClose,
  onStatusChange,
  onAddNote,
}) => {
  const [activeTab, setActiveTab] = useState<'summary' | 'transcript' | 'timeline' | 'notes' | 'audio'>('summary');
  const [newNote, setNewNote] = useState('');
  const [isChangingStatus, setIsChangingStatus] = useState(false);
  const [showAudioPlayer, setShowAudioPlayer] = useState(false);

  if (!isOpen || !candidate) return null;

  // Find linked call record if available
  const linkedCall = INITIAL_CALLS.find((c) => c.candidate_id === candidate.id) || INITIAL_CALLS[0];

  const handleNoteSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newNote.trim()) return;
    onAddNote(candidate.id, newNote.trim());
    setNewNote('');
  };

  const handleDownloadReport = () => {
    const reportText = `=====================================================
VOXHIRE.AI - CANDIDATE SCREENING REPORT
=====================================================
Candidate Name: ${candidate.name}
Role: ${candidate.role}
AI Readiness Score: ${candidate.ai_score} / 100
Screening Status: ${candidate.status}
Screening Date: ${candidate.call_date}

CONTACT DETAILS
Phone: ${candidate.phone}
Email: ${candidate.email}
Location: ${candidate.location}

EXPERIENCE & QUALIFICATIONS
Total Experience: ${candidate.experience_years} Years
Key Skills: ${candidate.skills.join(', ')}
Expected Compensation: ${candidate.expected_salary}
Notice Period / Availability: ${candidate.availability}

AI SUMMARY & DECISION SUPPORT
${linkedCall.summary?.experience_summary || 'Screened via automated workflow.'}
Primary Recommendation: ${linkedCall.summary?.ai_recommendation || 'Suitable for recruiter review.'}
Communication Rating: ${linkedCall.summary?.communication_rating || 'Good'}
Interest Level: ${linkedCall.summary?.interest_level || 'High'}

FULL CONVERSATION TRANSCRIPT
${linkedCall.transcript.map((t) => `[${t.formatted_time}] ${t.speaker.toUpperCase()}: ${t.text}`).join('\n')}

RECRUITER AUDIT NOTES
${candidate.recruiter_notes.map((n) => `- [${n.author_name} (${n.author_role})]: ${n.content}`).join('\n')}

=====================================================
Generated by VoxHire.AI Enterprise Telephony Engine
Notice: AI decision support output. Final human hiring review required.
=====================================================`;

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `VoxHire.AI-Report-${candidate.name.replace(/\s+/g, '_')}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-slate-950/80 backdrop-blur-sm animate-in fade-in">
      <div className="relative w-full max-w-4xl max-h-[92vh] bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl flex flex-col overflow-hidden text-slate-100">
        
        {/* Top Header */}
        <div className="px-6 py-5 border-b border-slate-800 bg-slate-950/70 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-center gap-4">
            {candidate.avatar_url ? (
              <img
                src={candidate.avatar_url}
                alt={candidate.name}
                referrerPolicy="no-referrer"
                className="w-14 h-14 rounded-xl object-cover border border-slate-700 shadow"
                onError={(e) => {
                  e.currentTarget.style.display = 'none';
                }}
              />
            ) : (
              <div className="w-14 h-14 rounded-xl bg-indigo-500/20 text-indigo-400 flex items-center justify-center font-bold text-xl border border-indigo-500/30">
                {candidate.name.charAt(0)}
              </div>
            )}

            <div>
              <div className="flex items-center gap-3">
                <h2 className="text-xl font-bold text-white">{candidate.name}</h2>
                <StatusBadge status={candidate.status} />
              </div>
              <p className="text-xs text-slate-400 mt-0.5">{candidate.role}</p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            {/* AI Score Badge */}
            <div className="px-3.5 py-1.5 rounded-xl bg-slate-900 border border-indigo-500/40 text-center">
              <span className="text-[10px] uppercase font-mono text-slate-400 block">AI Score</span>
              <span className="text-base font-mono font-bold text-indigo-400">
                {candidate.ai_score}/100
              </span>
            </div>

            <button
              onClick={onClose}
              className="p-2 min-h-[40px] min-w-[40px] flex items-center justify-center rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
              aria-label="Close modal"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Action Button Bar */}
        <div className="flex flex-wrap items-center justify-between gap-3 px-6 py-3 border-b border-slate-800 bg-slate-950/40 text-xs">
          <div className="flex items-center gap-2">
            <div className="relative">
              <button
                type="button"
                onClick={() => setIsChangingStatus(!isChangingStatus)}
                className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 font-medium transition-colors"
              >
                Change Status: <span className="text-indigo-400 font-semibold">{candidate.status}</span> ▾
              </button>

              {isChangingStatus && (
                <div className="absolute top-full left-0 mt-1 w-40 bg-slate-900 border border-slate-700 rounded-xl shadow-xl z-30 py-1">
                  {(['Shortlisted', 'Review', 'Not Suitable', 'Contacted', 'Hired'] as CandidateStatus[]).map((st) => (
                    <button
                      key={st}
                      type="button"
                      onClick={() => {
                        onStatusChange(candidate.id, st);
                        setIsChangingStatus(false);
                      }}
                      className="w-full text-left px-3 py-1.5 text-xs text-slate-300 hover:bg-slate-800 hover:text-white"
                    >
                      {st}
                    </button>
                  ))}
                </div>
              )}
            </div>

            <button
              type="button"
              onClick={() => setShowAudioPlayer(!showAudioPlayer)}
              className="px-3 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white font-medium flex items-center gap-1.5 transition-colors shadow-sm"
            >
              <Volume2 className="w-3.5 h-3.5" />
              <span>{showAudioPlayer ? 'Hide Audio Player' : 'Listen to Call'}</span>
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleDownloadReport}
              className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 font-medium flex items-center gap-1.5 transition-colors"
            >
              <Download className="w-3.5 h-3.5 text-cyan-400" />
              <span>Download Report</span>
            </button>
          </div>
        </div>

        {/* Optional Audio Player drawer */}
        {showAudioPlayer && (
          <div className="p-4 bg-slate-950 border-b border-slate-800 animate-in slide-in-from-top-2">
            <AudioPlayerWidget
              title={`Call Audio · ${candidate.name}`}
              speakerName={`Recruitment Assistant with ${candidate.name}`}
              durationSeconds={linkedCall.duration_seconds || 261}
            />
          </div>
        )}

        {/* Navigation Tabs */}
        <div className="flex items-center gap-2 px-4 sm:px-6 pt-2 border-b border-slate-800 bg-slate-950/20 text-xs font-medium overflow-x-auto whitespace-nowrap scrollbar-none pb-1">
          <button
            onClick={() => setActiveTab('summary')}
            className={`pb-2.5 px-3 border-b-2 transition-colors shrink-0 ${
              activeTab === 'summary'
                ? 'border-indigo-500 text-indigo-400'
                : 'border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            Candidate Profile &amp; Summary
          </button>
          <button
            onClick={() => setActiveTab('transcript')}
            className={`pb-2.5 px-3 border-b-2 transition-colors shrink-0 ${
              activeTab === 'transcript'
                ? 'border-indigo-500 text-indigo-400'
                : 'border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            Full Call Transcript
          </button>
          <button
            onClick={() => setActiveTab('timeline')}
            className={`pb-2.5 px-3 border-b-2 transition-colors shrink-0 ${
              activeTab === 'timeline'
                ? 'border-indigo-500 text-indigo-400'
                : 'border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            Call Timeline
          </button>
          <button
            onClick={() => setActiveTab('notes')}
            className={`pb-2.5 px-3 border-b-2 transition-colors shrink-0 ${
              activeTab === 'notes'
                ? 'border-indigo-500 text-indigo-400'
                : 'border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            Recruiter Notes ({candidate.recruiter_notes.length})
          </button>
        </div>

        {/* Modal Scrollable Body */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          
          {activeTab === 'summary' && (
            <div className="space-y-6">
              
              {/* Candidate Info Grid */}
              <div className="p-4 rounded-xl bg-slate-950/70 border border-slate-800">
                <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3">
                  Candidate Information
                </h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 text-xs">
                  <div>
                    <span className="text-slate-400 block">Phone</span>
                    <span className="font-mono text-slate-200 font-medium">{candidate.phone}</span>
                  </div>
                  <div>
                    <span className="text-slate-400 block">Email</span>
                    <span className="text-slate-200 font-medium">{candidate.email}</span>
                  </div>
                  <div>
                    <span className="text-slate-400 block">Experience</span>
                    <span className="text-slate-200 font-medium">{candidate.experience_years} Years</span>
                  </div>
                  <div>
                    <span className="text-slate-400 block">Location</span>
                    <span className="text-slate-200 font-medium">{candidate.location}</span>
                  </div>
                  <div>
                    <span className="text-slate-400 block">Availability</span>
                    <span className="text-slate-200 font-medium">{candidate.availability}</span>
                  </div>
                  <div>
                    <span className="text-slate-400 block">Expected Salary</span>
                    <span className="text-emerald-400 font-semibold">{candidate.expected_salary}</span>
                  </div>
                </div>
              </div>

              {/* Skills Section */}
              <div className="p-4 rounded-xl bg-slate-950/70 border border-slate-800">
                <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3">
                  Skills Assessment
                </h3>
                <div className="flex flex-wrap gap-2">
                  {candidate.skills.map((skill, idx) => (
                    <span
                      key={idx}
                      className="px-2.5 py-1 rounded-md bg-slate-900 border border-slate-700/80 text-xs text-indigo-300 font-medium"
                    >
                      {skill}
                    </span>
                  ))}
                </div>
              </div>

              {/* AI Call Summary */}
              {linkedCall.summary && (
                <div className="p-5 rounded-xl bg-slate-950/80 border border-indigo-500/30 space-y-3">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2 text-indigo-400 font-semibold text-xs uppercase tracking-wider">
                      <Sparkles className="w-4 h-4" />
                      <span>AI Call Summary &amp; Decision Support</span>
                    </div>
                    <span className="text-xs font-mono text-emerald-400">
                      Overall Score: {linkedCall.summary.overall_score}/100
                    </span>
                  </div>

                  <p className="text-xs sm:text-sm text-slate-200 leading-relaxed">
                    {linkedCall.summary.experience_summary}
                  </p>

                  <div className="p-3 rounded-lg bg-indigo-950/30 border border-indigo-900/50">
                    <span className="text-xs font-semibold text-indigo-300 block mb-1">
                      Advisory Recommendation:
                    </span>
                    <p className="text-xs text-slate-300 italic">
                      &ldquo;{linkedCall.summary.ai_recommendation}&rdquo;
                    </p>
                  </div>

                  <div className="grid grid-cols-2 gap-3 text-xs pt-1">
                    <div>
                      <span className="text-slate-400">Communication Rating: </span>
                      <span className="font-semibold text-cyan-400">{linkedCall.summary.communication_rating}</span>
                    </div>
                    <div>
                      <span className="text-slate-400">Interest Level: </span>
                      <span className="font-semibold text-emerald-400">{linkedCall.summary.interest_level}</span>
                    </div>
                  </div>
                </div>
              )}

            </div>
          )}

          {activeTab === 'transcript' && (
            <div className="space-y-3">
              <div className="text-xs text-slate-400 flex items-center justify-between mb-2">
                <span>Call ID: <code>{linkedCall.id}</code></span>
                <span>Duration: {linkedCall.duration_formatted}</span>
              </div>

              {linkedCall.transcript.length > 0 ? (
                linkedCall.transcript.map((t) => (
                  <div
                    key={t.id}
                    className={`p-3 rounded-xl border text-xs leading-relaxed ${
                      t.speaker === 'ai'
                        ? 'bg-slate-950 border-indigo-900/40 text-slate-300'
                        : 'bg-indigo-950/20 border-cyan-900/30 text-slate-200'
                    }`}
                  >
                    <div className="flex items-center justify-between font-mono text-[11px] mb-1 text-slate-400">
                      <span className={t.speaker === 'ai' ? 'text-indigo-400 font-bold' : 'text-cyan-400 font-bold'}>
                        {t.speaker === 'ai' ? 'VoxHire.AI (Aria)' : `${candidate.name}`}
                      </span>
                      <span>{t.formatted_time}</span>
                    </div>
                    <p>&ldquo;{t.text}&rdquo;</p>
                  </div>
                ))
              ) : (
                <div className="p-8 text-center text-slate-500 text-xs">
                  No transcript records found for this call.
                </div>
              )}
            </div>
          )}

          {activeTab === 'timeline' && (
            <div className="space-y-4">
              <div className="relative pl-6 space-y-6 before:absolute before:left-2 before:top-2 before:bottom-2 before:w-0.5 before:bg-slate-800">
                {candidate.timeline.map((item, idx) => (
                  <div key={idx} className="relative">
                    <div className="absolute -left-6 top-1 w-2.5 h-2.5 rounded-full bg-indigo-500 ring-4 ring-slate-900" />
                    <div className="text-xs font-semibold text-white">{item.title}</div>
                    <div className="text-[11px] font-mono text-slate-400">{item.timestamp}</div>
                    <p className="text-xs text-slate-400 mt-1">{item.description}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {activeTab === 'notes' && (
            <div className="space-y-4">
              {/* Add Note Form */}
              <form onSubmit={handleNoteSubmit} className="space-y-2">
                <label className="block text-xs font-medium text-slate-300">
                  Add Recruiter Audit Note
                </label>
                <textarea
                  value={newNote}
                  onChange={(e) => setNewNote(e.target.value)}
                  placeholder="Enter assessment details, technical remarks, or interview scheduling instructions..."
                  rows={3}
                  className="w-full p-3 bg-slate-950 border border-slate-800 rounded-xl text-xs text-white placeholder-slate-500 focus:outline-none focus:border-indigo-500"
                />
                <div className="flex justify-end">
                  <button
                    type="submit"
                    className="px-4 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-medium flex items-center gap-1.5 transition-colors"
                  >
                    <Plus className="w-3.5 h-3.5" />
                    <span>Save Note</span>
                  </button>
                </div>
              </form>

              {/* Existing Notes List */}
              <div className="space-y-3 pt-4 border-t border-slate-800">
                {candidate.recruiter_notes.length > 0 ? (
                  candidate.recruiter_notes.map((note) => (
                    <div
                      key={note.id}
                      className="p-3.5 rounded-xl bg-slate-950/60 border border-slate-800 text-xs space-y-1.5"
                    >
                      <div className="flex items-center justify-between text-slate-400">
                        <span className="font-semibold text-slate-200">
                          {note.author_name} <span className="text-indigo-400 font-normal">({note.author_role})</span>
                        </span>
                        <span className="font-mono text-[11px]">
                          {new Date(note.created_at).toLocaleDateString()}
                        </span>
                      </div>
                      <p className="text-slate-300 leading-relaxed">{note.content}</p>
                    </div>
                  ))
                ) : (
                  <p className="text-xs text-slate-500 text-center py-4">
                    No recruiter notes recorded yet. Add the first note above.
                  </p>
                )}
              </div>
            </div>
          )}

        </div>

        {/* Modal Footer */}
        <div className="flex items-center justify-between px-6 py-3.5 border-t border-slate-800 bg-slate-950/70 text-xs">
          <span className="text-slate-400">
            Last updated: <span className="text-slate-300">{candidate.call_date}</span>
          </span>
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 transition-colors"
          >
            Close
          </button>
        </div>

      </div>
    </div>
  );
};
